Repository dnd-side-project/dnd-6th-1-backend, pull requests merged in 2022-02, with the labels that each got.

#16 [FEAT] 회원가입 기능 구현
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/auth-credential.dto.ts
  src/auth/get-user.decorator.ts
  src/auth/jwt.strategy.ts
  src/auth/user.entity.ts
  src/auth/user.repository.ts
  src/boards/boards.controller.ts
Labels: Feature, Priority: High, 다영, 회원관리

#28 [FEAT/ADD]: 카테고리명, 글쓴이 코드 추가 및 좋아요,북마크 API
  src/auth/auth.service.ts
  src/auth/user.entity.ts
  src/auth/user.repository.ts
  src/board-images/board-images.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.entity.ts
  src/boards/boards.module.ts
  src/boards/boards.repository.ts
  src/boards/boards.service.ts
  src/boards/bookmarks.repository.ts
  src/boards/dto/create-board-first.dto.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/update-board.dto.ts
  src/boards/entity/boards.entity.ts
  src/boards/entity/bookmarks.entity.ts
  src/boards/entity/likes.entity.ts
  src/boards/likes.repository.ts
  src/comments/comments.controller.ts
  src/comments/comments.entity.ts
  src/comments/comments.module.ts
  src/comments/comments.repository.ts
Labels: Chore, Priority: Critical, 커뮤니티, 은주, Add

#34 Develop
  package.json
  src/boards/boards.controller.ts
  src/boards/boards.repository.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board-first.dto.ts
  src/boards/dto/create-board.dto.ts
  src/boards/entity/boards.entity.ts
  src/configs/typeorm.config.ts
  src/upload.option.ts
Labels: Fix, Priority: High, 커뮤니티, 은주

#38 Develop
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/users-credential.dto.ts
  src/auth/get-user.decorator.ts
  src/auth/jwt.strategy.ts
  src/auth/users.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.repository.ts
  src/boards/boards.service.ts
  src/boards/entity/boards.entity.ts
  src/boards/entity/bookmarks.entity.ts
  src/boards/entity/likes.entity.ts
  src/comments/comments.module.ts
  src/configs/typeorm.config.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Feature, Priority: High, 마이페이지, 커뮤니티, 은주, Add

#41 [FIX]: JWTService 오류 해결
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/boards/boards.service.ts
  src/comments/comments.module.ts
Labels: Fix, 은주, 회원관리

#42 Develop
  src/boards/boards.controller.ts
  src/boards/boards.repository.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Feature, Priority: Medium, 마이페이지, 은주

#45 [ADD] 회원가입 API Swagger 수정
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
Labels: Priority: High, 다영, 회원관리, Add

#46 [REFACTOR]: 커뮤니티 글 수정/삭제 시 이미지 처리
  src/board-images/board-images.entity.ts
  src/board-images/board-images.repository.ts
  src/boards/boards.controller.ts
  src/boards/boards.module.ts
  src/boards/boards.repository.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/dto/update-board.dto.ts
  src/boards/upload.service.ts
  src/main.ts
Labels: Priority: High, Refactor, 커뮤니티, 은주, Add

#50 Develop
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/entity/boards.entity.ts
  src/boards/repository/boards.repository.ts
  src/boards/repository/bookmarks.repository.ts
  src/boards/repository/likes.repository.ts
Labels: Priority: High, 커뮤니티, 은주

#52 develop
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/auth-signin.dto.ts
  src/auth/users.entity.ts
  src/profile-image/profile-image.entity.ts
  src/profile-image/profile-image.module.ts
  src/profile-image/profile-image.repository.ts
Labels: Priority: Medium, 다영, 회원관리, Add

#53 Develop
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/get-user.decorator.ts
  src/auth/jwt/jwt.guard.ts
  src/auth/jwt/jwt.strategy.ts
  src/board-images/board-images.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/entity/bookmarks.entity.ts
  src/boards/entity/histories.entity.ts
  src/boards/entity/likes.entity.ts
  src/boards/repository/bookmarks.repository.ts
  src/boards/repository/likes.repository.ts
  src/main.ts
Labels: Fix, Priority: Critical, 커뮤니티, 은주, Add

#55 Develop
  src/auth/auth.module.ts
  src/auth/dto/auth-signin.dto.ts
  src/auth/jwt/jwt.strategy.ts
  src/auth/users.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.module.ts
  src/boards/boards.service.ts
  src/boards/dto/create-board.dto.ts
  src/boards/repository/boards.repository.ts
  src/comments/comments.controller.ts
  src/comments/comments.repository.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.dto.ts
  src/users/users.repository.ts
Labels: Priority: Critical, 커뮤니티, 은주, Add

#57 Develop
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/auth/dto/auth-credential.dto.ts
  src/auth/dto/auth-signin.dto.ts
  src/boards/boards.controller.ts
  src/boards/boards.module.ts
  src/boards/boards.service.ts
  src/boards/repository/histories.repository.ts
  src/boards/upload.service.ts
  src/main.ts
  src/profile-image/profile-image.entity.ts
  src/profile-image/profile-image.module.ts
  src/profile-image/profile-image.repository.ts
  src/users/dto/update-profile.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Feature, Fix, 마이페이지, 커뮤니티, 은주, 회원관리, Add

#59 Develop
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/dto/auth-signin.dto.ts
  src/auth/users.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/main.ts
  src/users/dto/password.dto.ts
  src/users/users.controller.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Feature, 마이페이지, 은주, Add

#61 Develop
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.controller.ts
  src/boards/boards.controller.ts
  src/comments/comments.controller.ts
  src/main.ts
  src/users/users.controller.ts
Labels: Chore, Priority: Medium, 은주

#63 [FEAT] 다이어리 글 작성 API
  src/app.module.ts
  src/auth/users.entity.ts
  src/diaries/diaries.controller.ts
  src/diaries/diaries.entity.ts
  src/diaries/diaries.module.ts
  src/diaries/diaries.repository.ts
  src/diaries/diaries.service.ts
  src/diaries/dto/create-diary.dto.ts
  src/diaries/upload.service.ts
  src/diary-images/diary-images.entity.ts
  src/diary-images/diary-images.module.ts
  src/diary-images/diary-images.repository.ts
Labels: Feature, Priority: Critical, 홈(다이어리)탭, 다영

#68 [FIX] 이미지 없을 시 리턴 값 오류
  private-key.json
  src/boards/boards.controller.ts
  src/boards/upload.service.ts
  src/main.ts
Labels: Fix, 커뮤니티, 은주

#69 [MOD] 좋아요/북마크 함수 1개로 통일
  src/app.module.ts
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/repository/bookmarks.repository.ts
  src/boards/repository/likes.repository.ts
Labels: 커뮤니티, 은주

#70 [ADD] 일기글 작성, 조회 연도 추가
  src/diaries/diaries.controller.ts
  src/diaries/diaries.repository.ts
  src/diaries/diaries.service.ts
Labels: Priority: High, 홈(다이어리)탭, 다영, Add

#73 [MOD] 커뮤니티 글 최신순 정렬
  src/boards/boards.controller.ts
  src/boards/repository/boards.repository.ts
Labels: 커뮤니티, 은주

#74 [MOD] 커뮤니티 상세글 이미지 Response 변경
  src/boards/boards.service.ts
  src/users/users.controller.ts
Labels: 커뮤니티, 은주, Modify

#75 [ADD] 댓글 조회 시 commentId 추가
  src/boards/boards.service.ts
Labels: 커뮤니티, 은주, Add

#76 [FEAT] 일기글 수정, 삭제 API
  src/diaries/diaries.controller.ts
  src/diaries/diaries.repository.ts
  src/diaries/diaries.service.ts
  src/diaries/dto/update-diary.dto.ts
  src/diaries/upload.service.ts
Labels: Feature, Priority: High, 홈(다이어리)탭, 다영, Add

#77 [FIX] GET 요청 인식 오류 해결
  src/users/users.controller.ts
Labels: Fix, 커뮤니티, 은주

#78 [ADD] 로그인 response에 userId 추가
  src/auth/auth.controller.ts
Labels: 은주, 회원관리, Add

#80 Develop
  src/boards/boards.module.ts
  src/comments/comments.module.ts
  src/diaries/diaries.controller.ts
  src/diaries/diaries.repository.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Feature, 마이페이지, 은주

#81 [MOD] 커뮤니티 글 작성 response 수정
  src/boards/boards.controller.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 커뮤니티, 은주, Modify

#82 [MOD] 글 수정 API 코드 변경
  src/boards/boards.controller.ts
  src/users/users.service.ts
Labels: 커뮤니티, 은주, Modify

#83 [ADD] 감정순위 중복인 경우 모든 카테고리별 일기 반환
  src/users/users.service.ts
Labels: 마이페이지, 은주, Add

#84 [MOD] 커뮤니티 글 상세 조회 시 response 형식 변경
  src/boards/boards.service.ts
Labels: 커뮤니티, 은주, Modify

#86 [FIX] 삭제된 글 상세페이지 조회안되도록 수정
  src/boards/repository/boards.repository.ts
Labels: Fix, 커뮤니티, 은주

#87 Develop
  src/boards/boards.controller.ts
  src/boards/boards.service.ts
  src/boards/repository/boards.repository.ts
Labels: Fix, 커뮤니티, 은주

#88 [FIX] 마이페이지 글 조회 시 이미지 개수 정수형으로 변경
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Fix, 마이페이지, 은주

#89 [CHORE] : 일기글 조회 response 수정
  src/diaries/diaries.controller.ts
  src/diaries/diaries.repository.ts
  src/diaries/diaries.service.ts
  src/diaries/dto/create-diary.dto.ts
Labels: Chore, Priority: Critical, 홈(다이어리)탭, 다영

#90 [FIX] 마이페이지 내가 쓴 글 이미지 개수 반영 수정
  src/users/users.repository.ts
Labels: Fix, 마이페이지, 은주

#91 [CHORE]: 월 일기글 조회 response 수정
  src/diaries/diaries.repository.ts
  src/diaries/diaries.service.ts
Labels: Chore, Priority: Critical, 홈(다이어리)탭, 다영

#92 [ADD] 커뮤니티 특정 글에 boardId 추가
  src/boards/boards.service.ts
Labels: 커뮤니티, 은주, Add

#93 [CHORE]: 일기글 작성 response 수정
  src/diaries/diaries.service.ts
Labels: Chore, Priority: Critical, 홈(다이어리)탭, 다영

#94 [ADD] 마이페이지 통합 글 조회
  src/auth/dto/auth-signin.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 마이페이지, 은주, Add

#95 [FIX] 일기글 CRUD 오류 수정, response 수정
  src/auth/auth.controller.ts
  src/diaries/diaries.controller.ts
  src/diaries/diaries.repository.ts
  src/diaries/upload.service.ts
Labels: Bug, Fix, Hotfix, Priority: High, 홈(다이어리)탭, 다영

#100 [ADD] 커뮤니티/마이페이지 최근활동 기록 추가
  src/boards/boards.service.ts
  src/boards/repository/boards.repository.ts
  src/comments/comments.controller.ts
  src/comments/comments.repository.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: 마이페이지, 커뮤니티, 은주, Add

#101 [DEL] 파일 삭제
  .gitignore
  .gitmessage.txt
  private-key.json
Labels: 은주
