Repository dnd-side-project/dnd-6th-1-backend, pull requests merged in 2022-03, with the labels that each got.

#103 [FIX] 댓글 삭제/수정 권한 오류 수정
  .gitignore
  package-lock.json
  package.json
  src/alarm/alarm.controller.ts
  src/alarm/alarm.service.ts
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/boards/boards.module.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/diaries/diaries.entity.ts
  src/diaries/diaries.service.ts
  src/mail/email.ts
  src/mail/mail.controller.ts
  src/mail/mail.module.ts
  src/mail/mail.service.ts
  src/main.ts
  src/reports/create-report.dto.ts
  src/reports/reports.entity.ts
  src/reports/reports.repository.ts
  src/reports/reports.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Fix, 커뮤니티, 은주, Add, Modify

#105 [FIX] 커뮤니티 검색어 중복 시 시간만 업데이트
  src/app.module.ts
  src/auth/users.entity.ts
  src/boards/boards.controller.ts
  src/boards/boards.module.ts
  src/comments/comments.module.ts
  src/diaries/diaries.service.ts
  src/histories/histories.entity.ts
  src/histories/histories.repository.ts
  src/histories/histories.service.ts
  src/reports/create-report.dto.ts
  src/reports/reports.repository.ts
  src/reports/reports.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Fix, 커뮤니티, 은주

#106 [FIX] 다이어리 이미지 URL 수정
  src/diaries/upload.service.ts
  src/reports/reports.service.ts
Labels: Fix, 홈(다이어리)탭, 은주

#107 [FIX] 다이어리 주차 계산 오류 수정, 이미지 수정 API 오류 수정
  package-lock.json
  package.json
  src/alarm/alarm.service.ts
  src/auth/users.entity.ts
  src/boards/boards.module.ts
  src/comments/comments.module.ts
  src/diaries/diaries.controller.ts
  src/diaries/diaries.module.ts
  src/diaries/diaries.service.ts
  src/diaries/emotions.service.ts
  src/diaries/entity/diaries.entity.ts
  src/diaries/entity/emotions.entity.ts
  src/diaries/repository/diaries.repository.ts
  src/diaries/repository/emotions.repository.ts
  src/diary-images/diary-images.entity.ts
  src/diary-images/diary-images.repository.ts
  src/reports/reports.service.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: Fix, Hotfix, Priority: High, 홈(다이어리)탭, 다영

#109 [ADD] 일기글 작성 API response 수정
  package-lock.json
  package.json
  src/auth/dto/auth-signin.dto.ts
  src/diaries/diaries.controller.ts
  src/diaries/diaries.service.ts
Labels: Priority: High, 홈(다이어리)탭, 다영, Add

#110 [FEAT] 레포트 자동 생성 API
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/dto/auth-signin.dto.ts
  src/auth/get-user.decorator.ts
  src/auth/jwt/jwt.strategy.ts
  src/boards/entity/boards.entity.ts
  src/boards/entity/bookmarks.entity.ts
  src/boards/entity/likes.entity.ts
  src/configs/typeorm.config.ts
  src/diaries/diaries.service.ts
  src/diaries/entity/diaries.entity.ts
  src/diaries/repository/diaries.repository.ts
  src/histories/histories.entity.ts
  src/reports/reports.entity.ts
  src/reports/reports.repository.ts
  src/reports/reports.service.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.repository.ts
  src/users/users.service.ts
Labels: Fix, Priority: Critical, 마이페이지, 은주, Add, Modify

#111 [MOD] 마이페이지 Guard 주석 해제
  src/users/users.controller.ts
Labels: 마이페이지, 은주, Modify

#112 [ADD] 로그인 / 로그아웃 토큰 코드 추가
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/configs/typeorm.config.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.service.ts
Labels: Fix, 은주, 회원관리, Add

#113 [MOD] 주석 처리
  src/configs/typeorm.config.ts
Labels: 은주, Modify

#114 [FEAT] 비밀번호 찾기 / 임시비밀번호 발급 API
  package-lock.json
  package.json
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.repository.ts
  src/auth/auth.service.ts
  src/configs/typeorm.config.ts
Labels: Feature, Priority: High, 은주, 다영, 회원관리

#115 [FIX] 비밀번호 업데이트 수정
  src/auth/auth.repository.ts
Labels: Fix, Priority: Critical, 홈(다이어리)탭, 은주

#116 [ADD] 레포트에 프로필 이미지 추가
  src/auth/auth.service.ts
  src/reports/reports.service.ts
Labels: Fix, Add

#117 [MOD] 레포트 주차 데이터 정렬 변경
  src/reports/reports.service.ts
Labels: 마이페이지, 은주, Modify

#118 [CHORE] 로그인 시 없는 회원 응답 수정 / 탈퇴 후 해당 닉네임 중복 허용
  src/auth/auth.controller.ts
  src/auth/auth.repository.ts
Labels: Chore, Priority: High, 다영, 회원관리, Modify

#120 [ADD] 회원가입 시, 이메일 중복 처리
  src/auth/auth.controller.ts
  src/users/users.repository.ts
Labels: Chore, Priority: High, 다영, 회원관리, Add

#121 [CHORE] 회원탈퇴 API 수정
  src/users/users.repository.ts
Labels: Chore, Priority: Critical, 다영, 회원관리
